name: Auto-Deploy

on:
  push:
    branches: [ main ]

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Hub Update API
        run: |
          curl -X POST http://172.16.1.30:8000/setup/update
